first draft Organization Methodology
DuplosFidibuss/academic-time-planner pull request #17
Opened 2022-10-02 14:26 UTC by Ra1nerZufall

add bib entry for scrum

2022-10-02 14:32 UTC, Ra1nerZufall commented
Maybe the bib entry has to be changed. (The one in the BA looks different)

2022-10-03 13:05 UTC, DuplosFidibuss requested changes

2022-10-03 13:05 UTC, DuplosFidibuss commented on doc/parts/vorgehen_methoden.tex
> +For this project a reduced and modified version of SCRUM \cite{scrum_url} was chosen. This modifications include only two to three meetings a week, as we do not work on the project full time. This me
One more "one-liner" ...

Some suggestions:
- "These modifications include reducing the daily Scrum meeting to two or three meetings a week".
- Generally use the past (as our predecessors did, because it is seen as from a looking-back perspective).
- "One of these meetings, usually held on Tuesday morning, was attended by our project supervisor, Prof. Feisthammel as well. There, a short progress report as well as the weekly goals were discussed."
- I think milestones are defined and not included. I'd also split the sentence like this: "... have been defined. They roughly correspond with the two-week sprint plan."

2022-10-03 14:04 UTC, DuplosFidibuss requested changes

2022-10-03 14:04 UTC, DuplosFidibuss commented on doc/parts/vorgehen_methoden.tex
> +For this project a reduced and modified version of SCRUM \cite{scrum_url} was chosen. These modifications include reducing the daily SCRUM meetings to two to three meetings a week, as we do not work
Maybe "the modifications" instead of "these modifications".
And "as we did not work on the project" - should be past tense, too. And also "as we did something similar ...".

2022-10-03 14:31 UTC, Ra1nerZufall commented on doc/parts/vorgehen_methoden.tex
> +For this project a reduced and modified version of SCRUM \cite{scrum_url} was chosen. These modifications include reducing the daily SCRUM meetings to two to three meetings a week, as we do not work
Fixed

2022-10-03 14:34 UTC, DuplosFidibuss submitted a review, later dismissed

2022-10-03 14:38 UTC, DuplosFidibuss approved these changes

2022-10-03 14:39 UTC, merged