Backend/ferbemar/21 implement mapping concept
DuplosFidibuss/academic-time-planner pull request #33
Opened 2022-10-06 21:46 UTC by Ra1nerZufall

2022-10-07 11:52 UTC, DuplosFidibuss requested changes
As to code documentation, I'd suggest adding class descriptions for each class. It works as in Java, just write `///` instead of `/**` above the class declaration, and then the IDE will provide you with some XML tags you can add the class description.
As to the `PlanEntryRepetition` - have a look at my comments, if you do not understand them, it might be good to have a discussion about that anyway.

2022-10-07 11:52 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
> +        }
You should set the `_togglProjectId` here as well. It is good to have a separate constructor for this since you do not necessarily have a Toggl project id when you create a plan project. However, in this case the attribute should be set to a value indicating that there exists no according Toggl project yet. For instance, you could introduce a constant having the value -1 which is assigned to the Toggl project id in this constructor.

2022-10-07 11:52 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
> +        }
Again: assign a default value to the `_togglTaskId` to indicate that it has not yet been assigned to a Toggl task.

2022-10-07 11:52 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
> +        //TODO get all entry sums belonging to this task. List seems pointless as they are irrelevant after reading...
Not sure what you mean here - why would they be irrelevant? I'd go for a list, though.

2022-10-07 11:52 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
You do not need this method. You can create the plan entries directly in the constructor and add them to the list (maybe you want to create a private helper method for this and call it from the constructor).

2022-10-07 11:52 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
I know these are in the mapping concept, but they do not really make sense to me. What we need is RepetitionStartDate, RepetitionEndDate, interval and duration. That should suffice for creating the plan entries.

2022-10-07 11:52 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
These are not needed, since we do not add or remove single plan entries.

2022-10-07 11:52 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
You do not need this (see my comment above).

2022-10-07 11:52 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
Create an additional property `RepetitionStartDate`. In the setter methods of these two, you change the plan entries accordingly. Then you do not need the method `modifyPlanEntry` at all.

2022-10-07 12:03 UTC, Ra1nerZufall commented on AcademicTimePlanner/AcademicTimePlanner.csproj
> +    <Folder Include="DataMapping\Budget\" />
that line was generated automatically

2022-10-07 12:04 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Budget/Budget.cs
> +        }
good question. don't know.

2022-10-07 16:15 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
> +        }
there is no corresponding setter either.

2022-10-07 16:31 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
this means the entry itself has been modified, not the repetition of it.
this seems still pointless though.

2022-10-07 16:34 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
I have no idea how this would modify it anyway, it sounds more like a copy with different dates...

2022-10-07 16:34 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
See comment above.

2022-10-07 18:43 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        }
The only change - to my point of view - that you can do to a `PlanEntryRepetition` is that you either change duration, interval or start/end date (in fact, if you have a duration, you do not necessarily need an end date, but anyway). In all of these cases, you would have to change the single plan entries which are in the list.
Maybe we could discuss that to make sure we understood it correctly.

2022-10-07 18:50 UTC, DuplosFidibuss reviewed
Good changes. I think we need to discuss the `PlanEntryRepetition` as soon as possible.

2022-10-07 18:50 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +            _entries = planEntries;
You do not create the plan entries outside this class, so you do not have to hand this in the constructor. What you do on creating a `PlanEntryRepetition` is, you basically say, "create a series of plan entries, in this interval with this duration, between these dates". Therefore, the plan entries should be created within this class and not outside. You should create the plan entries here - that's at least how I understand the description, and somehow it makes sense to me.

2022-10-10 13:57 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
> +        //TODO get all entry sums belonging to this task. List seems pointless as they are irrelevant after reading...
added a List and an Add method for it.

2022-10-10 15:33 UTC, DuplosFidibuss requested changes
Please add class comments as discussed :-)

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Budget/Budget.cs
> +        private int _duration;
You do not need these any more. (See my previous comment with Mr Rege's slide.) Also goes for the other classes.

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Budget/Budget.cs
> +            _id = Guid.NewGuid();
`Id` (in other classes as well).

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
> +        public DateOnly StartDate { get; set; }
Please unify the vertical distances here. I am not sure whether we should add one empty line after each property or not. What do you think would be more readable? From my point of view, one line of distance would be OK. (Goes for other classes as well).

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
> +        }
We do not need this property, do we?

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +                if (start > _repetitionEndDate) { start = _repetitionEndDate; }
Please move the statement to a new line. You can delete the curly brackets; they are not needed for one-line ifs.

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +            //planEntry.Modified = true;
Please remove dead code.

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        {
You probably want to clear the list before filling in any new elements.

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
> +        private const int NoTogglId = -1;
I think it would be good to keep the good old policy that constants should be above variables. Also add an empty line between constant and variables.

2022-10-10 15:33 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Toggl/TogglEntrySum.cs
> +        public int TogglId { get; }
Did we not talk about our own id rather than the Toggl id? What you need from Toggl is the `TogglTaskId`.

2022-10-10 16:27 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +            //planEntry.Modified = true;
thats not really dead. it just doesn't work because a new Entry would not be modified. 
As we delete this property anyways it does not matter.

2022-10-10 16:27 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        {
good point.

2022-10-10 16:39 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
> +        public DateOnly StartDate { get; set; }
i would say one line apart is good.
this mistake was due to the look in vs. (it looked like there was a line in between)

2022-10-10 16:44 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Budget/Budget.cs
> +        private int _duration;
Ah I missed the part where it creates the variable.

2022-10-10 16:46 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Toggl/TogglEntrySum.cs
> +        public int TogglId { get; }
?
we have the togglId as well as the togglTaskId
will create an intern Id as well

2022-10-10 16:47 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Toggl/TogglEntrySum.cs
> +        public int TogglId { get; }
Ah right, I remember. Sorry for that confusion.

2022-10-10 18:11 UTC, DuplosFidibuss requested changes
Good work, just a couple of small corrections remaining.

2022-10-10 18:11 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +                    start = RepetitionEndDate;
I don't think that we should place an entry on the end date if start is greater than the end date. I would do it like this:
```csharp
if (start <= RepetitionEndDate)
    var planEntry = new PlanEntry(entryName, oldStart, start, Duration);

2022-10-10 18:11 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
> +        /// If no Toggle project islinked, the toggleProjectId will be -1.
is linked, not islinked.

2022-10-10 18:11 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
> +        /// A task can have multiple <see cref="PlanEntryRepetition"> plan entry repetiotions</see> and also
repetitions, not repetiotions.

2022-10-10 18:11 UTC, DuplosFidibuss commented on AcademicTimePlanner/DataMapping/Budget/Budget.cs
>          private LinkedList<PlanProjectBudget> _planProjectBudgets;
I would place the comment directly above the constructor (in the other classes as well).

2022-10-10 18:16 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +        /// The repetition has a start date which corresponds with the first date of the plan entries an dan end date.
this is a typo
[...] and an [...]
the space is at the wrong spot.

2022-10-10 18:19 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
> +                    start = RepetitionEndDate;
no
this means that the end date is not after the official end date.
start in this instance is the start of the next entry and the end of this one.
i just realized that that's not the right date, it should be a day before. but the point still stands.

2022-10-10 18:19 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
> +        /// If no Toggle project islinked, the toggleProjectId will be -1.
typo

2022-10-10 18:20 UTC, Ra1nerZufall commented on AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
> +        /// A task can have multiple <see cref="PlanEntryRepetition"> plan entry repetiotions</see> and also
ah i am getting tired all this typos :)

2022-10-10 18:32 UTC, DuplosFidibuss approved these changes

2022-10-10 18:32 UTC, merged