Documentation/ferbemar/55 describe pair programming in methods
DuplosFidibuss/academic-time-planner pull request #80
Opened 2022-11-11 17:33 UTC by Ra1nerZufall

2022-11-12 20:01 UTC, DuplosFidibuss requested changes

2022-11-12 20:01 UTC, DuplosFidibuss commented on doc/parts/methods.tex
> +Pair programming \cite{pairprogramming-url} is a form of programming where one person is writing code while the other person can focus on keeping an overview and helping finding solutions or research
Use "in which" instead of "where".
The whole first sentence is slightly too long. Could you split it up somewhere?
"... is preferable to be applied on exploring new and/or unknown technology as well as implementing complex code" - omit "and complicated".
"... can be discussed together. Moreover, the programmers would make fewer mistakes together since both of them are looking at the code."
"... second sprint, as unknown technology was used, and the implementation of loading and displaying data was fairly complex at first."

2022-11-14 14:08 UTC, Ra1nerZufall commented on doc/parts/methods.tex
> +Pair programming \cite{pairprogramming-url} is a form of programming where one person is writing code while the other person can focus on keeping an overview and helping finding solutions or research
Tried to rewrite the first sentence somewhat.

2022-11-14 17:14 UTC, DuplosFidibuss requested changes

2022-11-14 17:14 UTC, DuplosFidibuss commented on doc/parts/methods.tex
> +Pair programming \cite{pairprogramming-url} is a form of programming in which one person is writing code while the other person can focus on keeping an overview. The second person is also in charge o
Suggested improvements:
- "the first one" rather than "the other"
- "the solution agreed upon"
- "the likelihood ... is smaller"

2022-11-14 19:38 UTC, DuplosFidibuss approved these changes

2022-11-14 20:04 UTC, merged